repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files 
        exclude: .doc/videos/.*
      - id: debug-statements
      - id: check-json
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    - id: pyupgrade
      args: [--py311-plus]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ['--profile', 'black']

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ['--safe']
        language_version: python3.11

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: [
          "Flake8-pyproject",
          "flake8-bugbear",
          "flake8-variables-names",
          "flake8-builtins",
          ]
