global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'host'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'containers'

  - job_name: 'fastapi-prompt-injection-app'
    static_configs:
      - targets: ['prompt-injection-classifier-app:8000']
    metrics_path: '/metrics'