services:

  prompt-injection-classifier-app:
    build:
      context: ../../../
      dockerfile: deployment/docker/images/prompt-injection-classifier-app.Dockerfile
      target: runtime
    image: prompt-injection-classifier-app
    container_name: prompt-injection-classifier-app-container
    restart: unless-stopped
    env_file:
      - ../../../.env
    ports:
      - "${PROMPT_INJECTION_CLASSIFIER_APP_PORT}:8000"
    networks:
      - monitoring-network
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s